# Generated by Django 2.1.1 on 2018-10-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Data_Stored',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cpassword',
            field=models.CharField(default='0000000', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
